name: Build slack-notion-sync image

on:
  push:
    branches: [main]
    paths:
      - "test/**"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/slack-notion-sync

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and push to GHCR
        uses: ./.github/actions/docker-build-push-ghcr
        with:
          context: ./test
          registry: ${{ env.REGISTRY }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
